### ISSUE TITLE
add MergeBuilder

### ISSUE THREAD

**Issue by mschoch** [couchbaselabs/vellum#3]
The MergeBuilder would take n FST instances and a Writer as input, and produce a new FST containing the merged contents.  Implementation just has to create iterators on the underlying FSTs, walk them, and insert to the new one in order.

**Comment by jaytaylor** [comment]
I really like this idea.

Would there be a shortcut function, perhaps called something like `Add[Slowly]()` to "merge" a single record?

**Comment by jaytaylor** [comment]
I really like this idea.

Would there be a shortcut function, perhaps called something like `Add[Slowly]()`, to "merge" in a single record to an existing FST?

**Comment by seiflotfy** [comment]
Going to give it a try

**Comment by mschoch** [comment]
I'm actually working on a merging iterator right now, which would be one of the pieces needed.

**Comment by seiflotfy** [comment]
Yeah, I kept looking into merging one into another but that did not work, so the only solution was to iterate through both and insert into a new one. And it can be done in O(n+m), where n is length of the first and M being the length of the second. If we can iterate in a sorted order! WDYT?

**Comment by mschoch** [comment]
Yes, iterating both and building a new one is what I expected.

The piece I'm working on right now does 2 things:

1) make Iterator an interface (not strictly required for this phase, but enables a few other things later)

2) new MergingIterator which takes a slice of []Iterator

The purpose of this is to iterate all the underlying iterators and emit the union of the N iterators passed in.
Additionally, there is user callback to decide how to merge values when the same key is in multiple iterators.

Then, a merging builder of N FSTs just has to get an iterator for each, pass it into the MergingIterator, and then walk it, passing emitted key/value pairs to the new builder.
