### ISSUE TITLE
There are more typos

### ISSUE THREAD

**Issue by opennota** [couchbaselabs/vellum#5]
```
didnt
erorr
exptect
furhter
lexicogrpahic
opertion
purproses
revesed
wouldnt
```

in the following files:

```
decoder_v1_test.go
docs/format.md
encoder_v1.go
encoder_v1_test.go
fst.go
fst_iterator.go
fst_iterator_test.go
vellum.go
vellum_test.go
```

and a missing word in docs/format.md: This `***` us to get an early start on I/O

*Aside:* funnily enough, just yesterday I wrote my own implementation of DAWG/MA-FSA, which allowed me to save over 3 000 000 unicode words with associated part-of-speech tags to just 1.5Mb on disk (4 bytes per edge). With this implementation (without tuning) I get 14Mb.

**Comment by mschoch** [comment]
Thanks for reporting the typos.

The numbers you cite are an interesting data point.  My guess is that if we're 10x larger, it's not just the size of the edges, but also the number of them.  Was your implementation fully minimal?  Or also using a fixed-size registry?

**Comment by opennota** [comment]
There's nothing about any registry in the docs, as far as I can see. No, my implementation uses nothing of the kind and (I believe) contains minimal number of nodes/edges. I can't tell how many nodes or edges there are in the vellum case (and compare the numbers), because vellum doesn't provide interface for it.

**Comment by mschoch** [comment]
Ah yeah we're definitely not building a minimal FSA, we wanted to be able to easily put a bound on the memory used during the FSA construction.  So, we only remember a fixed number of states once they're serialized.  This means we later miss opportunities for reuse, but in our case thats a tradeoff we'll take.  This aspect of the approach is described in the "construction in practice" section of this blog: http://blog.burntsushi.net/transducers/

**Comment by opennota** [comment]
I see. Thanks for the clarification.

**Comment by mschoch** [comment]
@opennota by any chance is the dataset you're working with open?

**Comment by opennota** [comment]
@mschoch Yes,

http://opencorpora.org/?page=downloads

http://opencorpora.org/files/export/dict/dict.opcorpora.xml.bz2 (XML)

http://opencorpora.org/files/export/dict/dict.opcorpora.txt.bz2 (Plain text)

**Comment by mschoch** [comment]
Awesome, thanks.
