### ISSUE TITLE
inverted index

### ISSUE THREAD

**Issue by joeblew99** [couchbaselabs/vellum#6]
this can be used for an inverted index ?

**Comment by mschoch** [comment]
Not directly, but it could be one component in building one.

My current thinking is that this can be used to build the term dictionary portion of a new index scheme for bleve.  It tracks which terms are used in a field, and maps them to a uint64.  In the simplest case, that uint64 could be an offset location for where the postings list is stored.  The postings list actually tells you which documents used the term.

**Comment by joeblew99** [comment]
Ok makes sense. Nice.
I will close since this is not an issue.
